#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    May 02, 2019 02:02:35 AM +0700  platform: Windows NT

import sys
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_support
import pred_data, train_data, add_data,os
from tkinter import ttk, filedialog, messagebox
from PIL import Image, ImageTk

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = mainToplevel (root)
    main_support.init(root, top)
    root.mainloop()

w = None
def create_mainToplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = mainToplevel (w)
    main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_mainToplevel():
    global w
    w.destroy()
    w = None

class mainToplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#c5c8c9'  # X11 color: 'black'
        _fgcolor = '#c5c8c9'  # X11 color: 'black'
        _compcolor = '#718ec6' # X11 color: 'blue6'
        _ana1color = '#718ec6' # X11 color: 'blue6' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Times New Roman} -size 12 -weight normal -slant "  \
            "roman -underline 1 -overstrike 0"
        font11 = "-family {Times New Roman} -size 11 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font10 = "-family {Times New Roman} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        top.geometry("671x394+300+150")
        top.title("Halaman Awal")
        top.configure(background="#718ec6")
        top.configure(highlightbackground="#718ec6")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=-0.007, rely=-0.025, relheight=1.028
                , relwidth=1.006)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#c5c8c9")
        self.Frame1.configure(highlightbackground="#c5c8c9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=675)

        def add_data_show():
            root.destroy()
            add_data.vp_start_gui()
        self.addButton = tk.Button(self.Frame1, command=add_data_show)
        self.addButton.place(relx=0.04, rely=0.90, height=34, width=131)
        self.addButton.configure(activebackground="#ececec")
        self.addButton.configure(activeforeground="#000000")
        self.addButton.configure(background="#81a3a6")
        self.addButton.configure(disabledforeground="#a3a3a3")
        self.addButton.configure(foreground="#000000")
        self.addButton.configure(highlightbackground="#718ec6")
        self.addButton.configure(highlightcolor="black")
        self.addButton.configure(pady="0")
        self.addButton.configure(text='''TAMBAH DATA LATIH''')

        def train_data_show():
            root.destroy()
            train_data.vp_start_gui()
        self.trainButton = tk.Button(self.Frame1, command=train_data_show)
        self.trainButton.place(relx=0.29, rely=0.90, height=34, width=131)
        self.trainButton.configure(activebackground="#ececec")
        self.trainButton.configure(activeforeground="#000000")
        self.trainButton.configure(background="#81a3a6")
        self.trainButton.configure(disabledforeground="#a3a3a3")
        self.trainButton.configure(foreground="#000000")
        self.trainButton.configure(highlightbackground="#718ec6")
        self.trainButton.configure(highlightcolor="black")
        self.trainButton.configure(pady="0")
        self.trainButton.configure(text='''LATIH DATA''')

        def pred_data_show():
            root.destroy()
            pred_data.vp_start_gui()
        self.predictButton = tk.Button(self.Frame1, command=pred_data_show)
        self.predictButton.place(relx=0.54, rely=0.90, height=34, width=131)
        self.predictButton.configure(activebackground="#ececec")
        self.predictButton.configure(activeforeground="#000000")
        self.predictButton.configure(background="#81a3a6")
        self.predictButton.configure(disabledforeground="#a3a3a3")
        self.predictButton.configure(foreground="#000000")
        self.predictButton.configure(highlightbackground="#718ec6")
        self.predictButton.configure(highlightcolor="black")
        self.predictButton.configure(pady="0")
        self.predictButton.configure(text='''LAKUKAN PREDIKSI''')

        self.exitButton = tk.Button(self.Frame1,command=self.Exit)
        self.exitButton.place(relx=0.79, rely=0.90, height=34, width=131)
        self.exitButton.configure(activebackground="#ececec")
        self.exitButton.configure(activeforeground="#000000")
        self.exitButton.configure(background="#81a3a6")
        self.exitButton.configure(disabledforeground="#a3a3a3")
        self.exitButton.configure(foreground="#000000")
        self.exitButton.configure(highlightbackground="#718ec6")
        self.exitButton.configure(highlightcolor="black")
        self.exitButton.configure(pady="0")
        self.exitButton.configure(text='''EXIT''')

        self.titleLabel = tk.Label(self.Frame1)
        self.titleLabel.place(relx=0.133, rely=0.049, height=35, width=519)
        self.titleLabel.configure(activebackground="#718ec6")
        self.titleLabel.configure(activeforeground="white")
        self.titleLabel.configure(activeforeground="black")
        self.titleLabel.configure(background="#c5c8c9")
        self.titleLabel.configure(disabledforeground="#a3a3a3")
        self.titleLabel.configure(font=font9)
        self.titleLabel.configure(foreground="#000000")
        self.titleLabel.configure(highlightbackground="#ffb3ab")
        self.titleLabel.configure(highlightcolor="black")
        self.titleLabel.configure(text='''KLASIFIKASI CITRA RETINOBLASTOMA''')
        self.titleLabel.configure(width=519)

        self.titleLabel_1 = tk.Label(self.Frame1)
        self.titleLabel_1.place(relx=0.03, rely=0.123, height=35, width=650)
        self.titleLabel_1.configure(activebackground="#718ec6")
        self.titleLabel_1.configure(activeforeground="white")
        self.titleLabel_1.configure(activeforeground="black")
        self.titleLabel_1.configure(background="#c5c8c9")
        self.titleLabel_1.configure(disabledforeground="#a3a3a3")
        self.titleLabel_1.configure(font=font9)
        self.titleLabel_1.configure(foreground="#000000")
        self.titleLabel_1.configure(highlightbackground="#ffb3ab")
        self.titleLabel_1.configure(highlightcolor="black")
        self.titleLabel_1.configure(text='''BERDASARKAN GOLONGAN INTERNASIONAL DENGAN MENGGUNAKAN METODE''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.133, rely=0.198, height=35, width=519)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font9)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''CAPSULE NEURAL NETWORK (CAPSNet)''')

        self.imgCanvas = tk.Canvas(top)
        self.imgCanvas.configure(background="#c5c8c9")
        self.imgCanvas.configure(borderwidth="0")
        self.imgCanvas.configure(highlightbackground="#c5c8c9")
        self.imgCanvas.configure(highlightcolor="black")
        self.imgCanvas.configure(insertbackground="black")
        self.imgCanvas.configure(relief='ridge')
        self.imgCanvas.configure(selectbackground="#c4c4c4")
        self.imgCanvas.configure(selectforeground="black")
        self.imgCanvas.configure(width=243)
        img = ImageTk.PhotoImage(Image.open(os.path.dirname(os.path.realpath(__file__))+"/db/"+'logo usu.png').resize((100,100)))
        self.imgCanvas.image = img  # <--- keep reference of your image
        self.imgCanvas.create_image(0,0,anchor="nw",image=img)
        self.imgCanvas.pack()
        self.imgCanvas.place(relx=0.44, rely=0.26, height=100, width=100)

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.29, rely=0.52, height=20, width=300)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font11)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''OLEH: TAMA GUNA NAINGGOLAN''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.29, rely=0.57, height=20, width=300)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font11)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''151402074''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.22, rely=0.65, height=20, width=400)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font10)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''PROGRAM STUDI S1 TEKNOLOGI INFORMASI''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.22, rely=0.69, height=20, width=400)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font10)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''FAKULTAS ILMU KOMPUTER DAN TEKNOLOGI INFORMASI''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.22, rely=0.73, height=20, width=400)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font10)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''UNIVERSITAS SUMATERA UTARA''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.22, rely=0.77, height=20, width=400)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font10)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''MEDAN''')

        self.titleLabel_2 = tk.Label(self.Frame1)
        self.titleLabel_2.place(relx=0.22, rely=0.81, height=20, width=400)
        self.titleLabel_2.configure(activebackground="#718ec6")
        self.titleLabel_2.configure(activeforeground="black")
        self.titleLabel_2.configure(background="#c5c8c9")
        self.titleLabel_2.configure(disabledforeground="#a3a3a3")
        self.titleLabel_2.configure(font=font10)
        self.titleLabel_2.configure(foreground="#000000")
        self.titleLabel_2.configure(highlightbackground="#ffb3ab")
        self.titleLabel_2.configure(highlightcolor="black")
        self.titleLabel_2.configure(text='''2020''')

    def Exit(self):
        msg = messagebox.askyesno("Klasifikasi Gambar", "Apa Anda Yakin Ingin Keluar?")
        if(msg):
            exit()

if __name__ == '__main__':
    vp_start_gui()





