#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  May 03, 2019 03:36:04 AM +0700  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Segoe UI} -size 13 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d83838} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 744x527+315+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Prediksi"
    vTcl:DefineAlias "$top" "predToplevel" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Masukkan Gambar} 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "predToplevel" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Prediksi Tulisan Tangan} 
    vTcl:DefineAlias "$top.lab45" "Label1_14" vTcl:WidgetProc "predToplevel" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 164 -wrap word 
    .top42.tex46 configure -font TkTextFont
    .top42.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "imgText" vTcl:WidgetProc "predToplevel" 1
    button $top.but47 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but47" "imgBrowseButton" vTcl:WidgetProc "predToplevel" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Masukkan Model} 
    vTcl:DefineAlias "$top.lab48" "Label1_15" vTcl:WidgetProc "predToplevel" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Kemiringan 
    vTcl:DefineAlias "$top.lab49" "Label1_16" vTcl:WidgetProc "predToplevel" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Tegak 
    vTcl:DefineAlias "$top.lab50" "Label1_17" vTcl:WidgetProc "predToplevel" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Spasi 
    vTcl:DefineAlias "$top.lab51" "Label1_18" vTcl:WidgetProc "predToplevel" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 164 -wrap word 
    .top42.tex52 configure -font TkTextFont
    .top42.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "miringFileText" vTcl:WidgetProc "predToplevel" 1
    text $top.tex53 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 164 -wrap word 
    .top42.tex53 configure -font TkTextFont
    .top42.tex53 insert end text
    vTcl:DefineAlias "$top.tex53" "tegakFileText" vTcl:WidgetProc "predToplevel" 1
    text $top.tex54 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 164 -wrap word 
    .top42.tex54 configure -font TkTextFont
    .top42.tex54 insert end text
    vTcl:DefineAlias "$top.tex54" "spasiFileText" vTcl:WidgetProc "predToplevel" 1
    button $top.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but55" "miringBrowseButton" vTcl:WidgetProc "predToplevel" 1
    button $top.but56 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but56" "tegakBrowseButton" vTcl:WidgetProc "predToplevel" 1
    button $top.but57 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Browse 
    vTcl:DefineAlias "$top.but57" "spasiBrowseButton" vTcl:WidgetProc "predToplevel" 1
    button $top.but58 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Lakukan Prediksi} 
    vTcl:DefineAlias "$top.but58" "predButton" vTcl:WidgetProc "predToplevel" 1
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Hasil Prediksi} 
    vTcl:DefineAlias "$top.lab60" "Label1_19" vTcl:WidgetProc "predToplevel" 1
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr62 \
        -background {#d9d9d9} -height 15 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 30 
    vTcl:DefineAlias "$top.scr62" "summaryScrolledtreeview" vTcl:WidgetProc "predToplevel" 1
    canvas $top.can63 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 173 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 233 
    vTcl:DefineAlias "$top.can63" "img1Canvas" vTcl:WidgetProc "predToplevel" 1
    canvas $top.can64 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 173 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 233 
    vTcl:DefineAlias "$top.can64" "histEqimgCanvas" vTcl:WidgetProc "predToplevel" 1
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Gambar Awal} 
    vTcl:DefineAlias "$top.lab65" "Label1_21" vTcl:WidgetProc "predToplevel" 1
    label $top.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d83838} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Histogram Equalization} 
    vTcl:DefineAlias "$top.lab66" "Label1_22" vTcl:WidgetProc "predToplevel" 1
    button $top.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Halaman Awal} 
    vTcl:DefineAlias "$top.but45" "homeButton" vTcl:WidgetProc "predToplevel" 1
    button $top.but49 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Keluar 
    vTcl:DefineAlias "$top.but49" "exitButton" vTcl:WidgetProc "predToplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 80 -width 114 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 270 -y 30 -width 214 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 140 -y 80 -width 164 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 320 -y 80 -width 57 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 130 -width 124 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 160 -width 74 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 9 -y 191 -width 44 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 12 -y 222 -width 34 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 140 -y 160 -width 164 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex53 \
        -in $top -x 140 -y 190 -width 164 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tex54 \
        -in $top -x 140 -y 220 -width 164 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 320 -y 160 -width 57 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 320 -y 190 -width 57 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but57 \
        -in $top -x 320 -y 220 -width 57 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.but58 \
        -in $top -x 14 -y 260 -width 97 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 10 -y 320 -width 124 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr62 \
        -in $top -x 20 -y 350 -width 360 -relwidth 0 -height 147 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can63 \
        -in $top -x 470 -y 105 -width 233 -relwidth 0 -height 173 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.can64 \
        -in $top -x 470 -y 336 -width 233 -height 173 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x 470 -y 80 -width 84 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 470 -y 306 -width 144 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 550 -y 30 -width 87 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 640 -y 30 -width 87 -height 24 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

